#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomerMobileApplication.Resource", IsApplication=true)]

namespace CustomerMobileApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::CustomerMobileApplication.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::CustomerMobileApplication.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int locations = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int numbers = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int railcards = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int times = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Connected_Rail = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Logo_green = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int btnLogin = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int button_expiredTickets = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int button_makeBooking = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int button_refresh = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int button_searchTrains = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int button_viewTickets = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int checkBox_return = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int checkBox_single = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int checkBox_singleReturn = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int etInputEmail = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int etInputPassword = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int ivLoginLogo = 2131099664;
			
			// aapt resource value: 0x7f060019
			public const int listView_activeTickets = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int listView_expiredTickets = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int listView_trainsAvailable = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int listView_viewExpiredTicket = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int listView_viewTicket = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int spinner_adults = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int spinner_children = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int spinner_locationOne = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int spinner_locationTwo = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int spinner_outbound = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int spinner_railcards = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int spinner_return = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int textView_Cancel = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int textView_signout = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int tvForgottenPassword = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int tvRegister = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Active_Ticket = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Create_Booking = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Expired_Ticket = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Ticket_Search = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int View_Active_Tickets = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int View_Expired_Tickets = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
