//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int ID { get; set; }
        public Nullable<int> PASSENGER_ID { get; set; }
        public Nullable<int> JOURNEY_ID { get; set; }
        public string BOOKING_TYPE { get; set; }
        public string SEAT_NUMBER { get; set; }
        public string SEAT_PREFERENCE { get; set; }
        public System.DateTime DEPARTURE_DATE_TIME { get; set; }
        public decimal DEPARTURE_PLATFORM { get; set; }
        public System.DateTime ARRIVAL_DATE_TIME { get; set; }
        public decimal ARRIVAL_PLATFORM { get; set; }
    
        public virtual TRAIN_JOURNEY TRAIN_JOURNEY { get; set; }
        public virtual PASSENGER PASSENGER { get; set; }
    }
}
