//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRIAGE
    {
        public int ID { get; set; }
        public string CARRIAGE_CLASSIFICATION { get; set; }
        public Nullable<int> FREIGHT_COMPANY_ID { get; set; }
        public decimal TOTAL_NUMBER_OF_SEATS { get; set; }
        public decimal NUMBER_OF_AVAILABLE_SEATS { get; set; }
    
        public virtual TRAIN_CARRIAGES TRAIN_CARRIAGES { get; set; }
        public virtual TRAIN_COMPANIES TRAIN_COMPANIES { get; set; }
    }
}
