//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN
    {
        public int ID { get; set; }
        public Nullable<int> TRAIN_COMPANY_ID { get; set; }
        public string TRAIN_TYPE { get; set; }
        public string CARGO_TYPE { get; set; }
    
        public virtual TRAIN_CARRIAGES TRAIN_CARRIAGES { get; set; }
        public virtual TRAIN_COMPANIES TRAIN_COMPANIES { get; set; }
    }
}
