//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN_CARRIAGES
    {
        public int ID { get; set; }
        public int CARRIAGE_ID { get; set; }
        public int TRAIN_ID { get; set; }
    
        public virtual CARRIAGE CARRIAGE { get; set; }
        public virtual TRAIN TRAIN { get; set; }
    }
}
