/*
Input Test Data
*/
/* train company data*/
INSERT INTO TRAIN_COMPANIES (ID,COMPANY_NAME)
VALUES ('01', 'Western Rail');

INSERT INTO TRAIN_COMPANIES (ID,COMPANY_NAME)
VALUES ('2','Big Rail');

INSERT INTO TRAIN_COMPANIES (ID,COMPANY_NAME)
VALUES ('3','Carriage Co.');

INSERT INTO TRAIN_COMPANIES (ID,COMPANY_NAME)
VALUES ('4', 'Helpful Carriages');

/*location data*/
INSERT INTO LOCATIONS (ID,CITY_NAME,TRAIN_STATION_NAME, LATITUDE, LONGITUDE)
VALUES ('1','Plymouth','Plymouth Railway Station','50.3777318','-4.1430849');

INSERT INTO LOCATIONS (ID,CITY_NAME,TRAIN_STATION_NAME, LATITUDE, LONGITUDE)
VALUES ('2','Plymouth','Devonport Railway Station','50.378458','-4.1703182');

INSERT INTO LOCATIONS (ID,CITY_NAME,TRAIN_STATION_NAME, LATITUDE, LONGITUDE)
VALUES ('3','Ivybridge','Ivybridge Railway Station','50.3934037','-3.904761');

INSERT INTO LOCATIONS (ID,CITY_NAME,TRAIN_STATION_NAME, LATITUDE, LONGITUDE)
VALUES ('4','Totnes','Totnes Railway Station','50.4360055','-3.6889031');

INSERT INTO LOCATIONS (ID,CITY_NAME,TRAIN_STATION_NAME, LATITUDE, LONGITUDE)
VALUES ('5','Paignton','Paignton Railway Station','50.4345744','-3.5651534');

/*trains*/
INSERT INTO TRAINS (ID,TRAIN_COMPANY_ID, TRAIN_TYPE, CARGO_TYPE)
VALUES ('1', '2', 'Diesel', 'Passenger');

INSERT INTO TRAINS (ID,TRAIN_COMPANY_ID, TRAIN_TYPE, CARGO_TYPE)
VALUES ('2', '1', 'Diesel', 'Freight');

INSERT INTO TRAINS (ID,TRAIN_COMPANY_ID, TRAIN_TYPE, CARGO_TYPE)
VALUES ('3', '3', 'Diesel', 'Passenger');


/*
INSERT INTO STAFF (ID, EMAIL_ADDRESS,FIRST_NAME, LAST_NAME, GENDER, STAFF_ROLE)
VALUES ('1','thejedwards@hotmail.co.uk','John','Edwards', 'Other', 'Train Driver');
*/
