CREATE OR REPLACE TRIGGER TRG_ENSURE_STAFF_ACCOUNT_GENDER_VALID
BEFORE INSERT OR UPDATE OF GENDER ON STAFF FOR EACH ROW
BEGIN
    IF (:NEW.GENDER IS NOT NULL) THEN
        IF (UPPER(:NEW.GENDER) IN ('MALE', 'FEMALE', 'OTHER')) THEN
            RAISE_APPLICATION_ERROR(-20000, 'Error: A gender may only be set as: "Male", "Female" or "Other".');
        END IF;
    END IF;
END;
